google/kasan

- include/linux/kfence.h
- include/linux/slab.h
- init/main.c
- mm/Kconfig.debug
- mm/Makefile
- mm/huge_memory.c
- mm/kfence.c
- mm/slub.c
No error checking for now, we just steal the freelist from a random
kmalloc cache from time to time, and route SLUB's slow path into our
allocator that returns pages.
> kfence: initial allocation hookup prototype

- include/linux/kfence.h
- mm/kfence.c
* Add missing 'inline' in header.
* Add missing declarations in header.
* Add some TODOs.
* clang-format.
Signed-off-by: Marco Elver <elver@google.com>
> kfence: Various cleanups

- lib/test_kfence.c
- mm/kfence.c
Those didn't make sense in the first place: if we stole a freelist on
CPU0 and switched to CPU1 before reinstating it, the freelist contents
would've been stuck on CPU0.
> kfence: get rid of per-cpu variables

- mm/kfence.c
Use get_random_int() to select a random kmalloc cache and to place the
allocated object at the beginning/end of the page.
Also fix ksize() to handle both cases of object placement within the
page.
> kfence: use get_random_int()

- include/linux/kfence.h
- include/linux/slab.h
- lib/test_kfence.c
- mm/kfence.c
- mm/slab.h
- mm/slub.c
As Jann Horn once mentioned, we do not actually need `kfence_slab_cache` for any of our fast path magic. Removing it drags along other bits that are useless now.
> Get rid of kfence_slab_cache

- include/linux/slab.h
- lib/test_kfence.c
- mm/kfence/core.c
- mm/kfence/core.h
- mm/kfence/naive.c
- mm/slub.c
See https://github.com/google/kasan/issues/79
> Use canaries to detect non-fatal OOB writes.

- mm/kfence/core.c
- mm/kfence/kfence.h
- mm/kfence/report.c
Remove kfence_dump_buf and rework how objects are printed to either
seq_files or to console.
> kfence: Rework object printing

- include/linux/slab.h
Since the introduction of the inline function
kfence_sampled_alloc_with_size(), the call here is no longer necessary,
as it is implicitly done via kmem_cache_alloc_trace -> slab_alloc ->
slab_alloc_node.
Signed-off-by: Marco Elver <elver@google.com>
> kfence: Fix slab.h's kmalloc()

- include/linux/kfence.h
- lib/Kconfig.kfence
- mm/kfence/Makefile
- mm/kfence/static_key.c
This implements a sampling based method using static keys aka. jump
labels. Jump labels use code patching to turn on or off branches at
runtime. Typically the cost of enabling or disabling is high due to
IPIs, however, even with the default sample rate of 100ms, no measurable
performance degradation can be observed.
Doing a simple sysbench run shows that the overhead is negligible and no
performance difference to the non-KFENCE version is noticable. More
detailed results from sysbench run here:
https://github.com/google/kasan/issues/72
My proposal is that we make this variant the main sampling method of
interest, and if it survives further testing, remove all other sampling
methods in favor of simply having this one. This should hopefully also
get us closer to the preparation of a patch …
> kfence: Implement static key based sampling method

- lib/Kconfig.kfence
- mm/kfence/core.c
- mm/kfence/kfence.h
- mm/kfence/report.c
Unlike other debugging tools, we have a fixed number of allocations to
care about, so we'd better store the stacks ourselves to avoid the
growing memory consumption of stackdepot.
Fixes https://github.com/google/kasan/issues/66
> kfence: get rid of stack depot

- include/linux/kfence.h
- mm/kfence/core.c
Making __kfence_pool_start an array in the data section allows us to
check whether an address belongs to it or not without doing memory
loads.
This also required fixing kfence_force_4k_pages(), which didn't work
initially.
> kfence: statically allocate the memory pool

- mm/kfence/core.c
- mm/kfence/report.c
Test was unhappy after rebase. Seems something caused compiler to optimize more.
Signed-off-by: Marco Elver <elver@google.com>
> kfence: Fix get_stack_skipnr() with tail call optimization

- Documentation/dev-tools/kfence.rst
This is so that we can test the API documentation with 'make htmldocs'.
> kfence, Documentation: Include API for rendering documentation

- arch/arm64/Kconfig
- arch/arm64/include/asm/kfence.h
- arch/arm64/mm/fault.c
- arch/x86/Kconfig
- include/linux/kfence.h
- lib/Kconfig.kfence
- mm/kfence/core.c
- mm/kfence/kfence-test.c
- mm/kfence/report.c
Add support for ARM64.
It appears that the static pool cannot be used on ARM64 trivially, because it doesn't set up valid pages for statically allocated memory (at least `virt_to_page()` always returned an invalid page pointer). At some future point, we may want to try and understand if we can force it to give us some pages.
I will try to research more what exactly happens with .bss memory on ARM64 for the commit message. If you know what's happening, please let me know.
All tests pass in a VM (except the test_gfpzero is a bit flaky due to it not getting the same object back)!
(I'll wait to push this until your API documentation changes are in the repo, after which I'll do a rebase, as there are some conflicts.)
> Support ARM64

- arch/arm64/include/asm/kfence.h
- mm/kfence/core.c
As discussed, turn the ARM64 TODO into a FIXME, as it's optional to resolve before the RFC.
Also remove the TODO about merging the files, as it seems unnecessary for the RFC. If maintainers request consolidation, we'll happily merge them.
With that, we have only 1 non-formatting related TODO left in core.c. (And obviously the TODOs in Documentation, but no major TODOs left in code.)
> kfence: Address TODOs, and turn the ARM64 TODO into a FIXME

- mm/kfence/core.c
> kfence: fix kfence_debugfs_init() declaration, should be returning int

- kernel/locking/lockdep.c
Lockdep complains if certain structures are in static data. Exclude kfence memory.
If this problem keeps coming up again in other contexts, we might need to look for a better solution.
> Lockdep compatibility

- include/linux/kfence.h
- mm/kfence/core.c
- mm/kfence/kfence-test.c
This is to get the rebased patch-series ready. From this point on, we should probably use clang-format-diff.
I could probably just apply this to the kfence-rebase-wip branch, but it'll make cherry-picking onto + rebasing that branch more difficult.
> kfence: Remove clang-format on/off

- mm/kmemleak.c
As suggested by Catalin Marinas
> kfence: kmemleak: use delete_object_part() for KFENCE pool

- lib/Kconfig.kfence
- mm/kfence/Makefile
- mm/kfence/kfence_test.c
While it's easy to change, let's switch to what appears to be the final
naming guidelines:
https://lkml.kernel.org/r/20200909051631.2960347-1-davidgow@google.com
The major changes here are:
s/kfence-test/kfence_test/
s/KFENCE_TEST/KFENCE_KUNIT_TEST/
The config variable naming is already used by a bunch of tests in the
kernel. The filename change is a result of a longer discussion; the
change from '-' to ``_`` is motivated by the fact that the real module
name only contains ``_`` even if the filename contains '-'.
> kfence: test: More closely follow new naming guidelines

- mm/kfence/core.c
- mm/kfence/kfence.h
- do not store negative size for right-located objects
- only cache-align addresses of right-located objects
- run toggle_allocation_gate() after KFENCE is enabled
> kfence: v2: address comments by Dmitry Vyukov

- mm/kfence/core.c
There were 2 smaller fixes in the other PR. Specifically the tweak to allow changing sample_interval for all builds at runtime, and calling prandom_u32() only if needed.
I am somewhat worried that changing sample_interval at runtime can be abused (e.g. by curious sysadmins), but I suppose if you're root, you already own the system anyway.
Thanks,
-- Marco
> Minor fixes for v2

- mm/kfence/kfence_test.c
To avoid warnings of using more than 1024 bytes stack usage.
In a test run with a WARN_ON(256 > len) no warnings were triggered for
the test, and 256 bytes should still be enough.
> kfence: v3: Lower line buffer size

- mm/kfence/report.c
Found with Clang + linux-next + KFENCE.
> kfence: v4: Fix report generation if __slab_free tail-called

- mm/kasan/common.c
... as it may be called from SL*B internals, currently ksize().
Fixes https://github.com/google/kasan/issues/153
> kfence: v5: Also guard kasan_unpoison_shadow

- arch/arm64/mm/mmu.c
KFENCE requires that individual pages from its memory pool can be
individually marked as accessible/inaccessible, therefore we force
the entire linear map to be mapped at page granularity.
Doing so may result in extra memory allocated for page tables in the
case rodata=full is not set, but currently CONFIG_RODATA_FULL_DEFAULT_ENABLED
is the default, so the general case will not be affected by this change.
Suggested-by: Mark Rutland <mark.rutland@arm.com>
> kfence: arm64: force page granularity for the linear map

- arch/x86/include/asm/kfence.h
- lib/Kconfig.kfence
- mm/kasan/generic.c
- mm/kfence/core.c
- Changes to KFENCE_NUM_OBJECTS handling. FYI: Turns out actual max order is MAX_ORDER-1 (🤔). So in reality the max number of objects on e.g. x86 is only 511.
- New KASAN problems, because of using page_alloc.
- set_direct_map_{invalid,default}_noflush() does not work due to potential deadlock.
> More fixes for v5

- include/linux/kfence.h
- include/linux/slab_def.h
- include/linux/slub_def.h
- mm/kfence/core.c
- mm/kfence/kfence_test.c
- mm/slab.c
Fixes https://github.com/google/kasan/issues/164
One thing I don't like is that we are adding an include to the *def.h headers. These seem to want no headers? Although technically they should include their required headers... hopefully nobody will complain about us adding the kfence header (the only major include in kfence.h is mm.h).
> Fix kfence+memcg

- arch/arm64/include/asm/kfence.h
- arch/arm64/mm/fault.c
- arch/x86/include/asm/kfence.h
- arch/x86/mm/fault.c
- include/linux/kfence.h
- mm/kfence/core.c
- mm/kfence/kfence.h
- mm/kfence/report.c
To be sent as individual patch to LKML.
> kfence: Use pt_regs to generate stack trace on faults

- include/trace/events/error_report.h
- kernel/trace/Makefile
- kernel/trace/error_report-traces.c
- lib/Kconfig.debug
- lib/Makefile
- lib/error_report_notify.c
- mm/kasan/report.c
- mm/kfence/report.c
This patch series adds error report tracing for debugging tools like KFENCE and KASAN, so that it is possible to extend their error reporting mechanisms.
It also implements CONFIG_ERROR_REPORT_NOTIFY that captures the last error report and exposes it, together with the report count, to the userspace via sysfs.
This shall make it possible to perform userspace handling of memory errors (e.g. uploading them to the cloud) in restrictive environments that disallow access to dmesg or /dev/kmsg.
> error_report_notify implementation

- Documentation/admin-guide/kernel-parameters.txt
- Documentation/dev-tools/kfence.rst
- lib/Kconfig.kfence
- lib/test_bitmap.c
- lib/test_printf.c
- lib/vsprintf.c
- mm/kfence/core.c
- mm/kfence/kfence.h
- mm/kfence/kfence_test.c
- mm/kfence/report.c
- tools/testing/selftests/kselftest_module.h
If, as Peter said here [1], this gets included in 5.12, the "kfence: .." patch will be sent on Thursday/Friday hopefully in time.
[1] https://lkml.kernel.org/r/YCpWJWkssy7xkgV0@alley
> kfence: no_hash_pointers
